server:
  port: 8082


spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/microservice}
    username: postgres
    password: ravi
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect


  config:
    import: optional:configserver:http://${CONFIG_SERVER:localhost}:8085

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${SERVICE_REGISTRY:localhost}:8761/eureka

okta:
  oauth2:
    issuer: https://dev-02352501.okta.com/oauth2/default
    audience: api://default
